# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ADLINK zenoh team, <zenoh@adlink-labs.tech>
#
name: zephyr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        sudo apt-get install -y --no-install-recommends git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
          make gcc gcc-multilib g++-multilib libsdl2-dev

    - name: Install PlatformIO
      run: |
        python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
        . $HOME/.platformio/penv/bin/activate
        platformio update

    - name: Set up project
      run: |
        cd $HOME
        export ZEPHYR_BASE=$HOME/zephyrproject/
        . $HOME/.platformio/penv/bin/activate
        mkdir -p $ZEPHYR_BASE/zephyr
        cat << EOF > $ZEPHYR_BASE/zephyr/CMakeLists.txt
        cmake_minimum_required(VERSION 3.13.1)
        include(\$ENV{ZEPHYR_BASE}/cmake/app/boilerplate.cmake NO_POLICY_SCOPE)
        project(zenoh-pico-zephyr)

        target_sources(app PRIVATE ../lib/zenoh-pico/examples/net/zn_pub.c)
        EOF

        mkdir -p $ZEPHYR_BASE/lib
        cd $ZEPHYR_BASE/lib
        ln -s $HOME/zenoh-pico

        cd $ZEPHYR_BASE/zephyr
        ln -s $HOME/zenoh-pico/docs/zephyr/nucleo_f767zi/prj.conf prj.conf

        cd $ZEPHYR_BASE
        ln -s $HOME/zenoh-pico/docs/zephyr/nucleo_f767zi/platformio.ini platformio.ini

    - name: Build
      run: |
        export ZEPHYR_BASE=$HOME/zephyrproject/
        . $HOME/.platformio/penv/bin/activate
        cd $ZEPHYR_BASE
        platformio run
